### ISSUE TITLE
On Screen Rotation

### ISSUE THREAD

**Issue by grifas** [anas10/AASquaresLoading#2]
Hi Anas ;)

There is a bug when we rotate screen, the frame is not responsive with this use:
`<self.view.squareLoading.start(0.0)>`

Have you an idea ?

**Comment by anas10** [comment]
Sorry for the late reply. Could you give me more details ? A code snippet would be helpful.

**Comment by anas10** [comment]
I'm gonna close this one. Feel free to reopen if this is still happening.
Thank you for using AASquaresLoading ;)
