### ISSUE TITLE
Can we support Swift 3?

### ISSUE THREAD

**Issue by mdfalcon104** [anas10/AASquaresLoading#3]

**Comment by iLucas97** [comment]
Swift 3 support?

**Comment by townsendeb** [comment]
I can't wait until this works for Swift 3, This is my favorite loading module.

**Comment by anas10** [comment]
Thank you guys for your interest. 
I will add support for swift 3.0 soon.

**Comment by anas10** [comment]
I've updated the loading so that it can support swift3.0. 
I have also released a new version on Cocoapods.
If someone wants to use the swift 2.0 version there is a branch for it.

Let me know if it works well for you guys. And thank you for using it ;)
